cover: /img/bg_img.jpg
logo: /img/logo.png
logoc: /img/logoc.png
top_saying:
- title: GLAD TO SEE U, WELCOME TO Qi Tang &#39;S BLOG.  
- content: 世上哪有终点？什么时候你走不动了，倒下了，那里才是终点。—— 今何在《西游日记》
bottom_saying:  你不能把这个世界，让给你所鄙视的人。—— 安•兰德《源泉》
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
#duoshuo_shortname: 

# Disqus
disqus_shortname: tangqi92githubio

# Miscellaneous
GitHub: https://github.com/tangqi92
Twitter: https://twitter.com/tangqi92
Weibo: http://weibo.com/qiktang
ZhiHu: http://www.zhihu.com/people/tangqi92

# Links
links:
- name: 安卓同学
  link: http://tikitoo.me/
- name: poberWong
  link: http://lovinghuan.com/
- name: markzhai
  link: http://blog.zhaiyifan.cn/
- name: 程序亦非猿
  link: http://yifeiyuan.me/
- name: 阿布
  link: http://abner-nimengbo.cn/
- name: Ailurus
  link: http://www.easydone.cn/
- name: 吴小龙同學
  link: http://wuxiaolong.me/
- name: Drakeet
  link: http://drakeet.me/
- name: 方杰
  link: http://blog.fangjie.info/
- name: 五道口宅男
  link: http://hujiaweibujidao.github.io/